language: node_js
node_js:
 - "6.1"

# https://docs.travis-ci.com/user/customizing-the-build/#Git-Clone-Depth
git:
  depth: 10

# https://docs.travis-ci.com/user/languages/javascript-with-nodejs#Node.js-v4-(or-io.js-v3)-compiler-requirements
addons:
  browserstack:
    username:
      secure: "gySOgWeMHSZtWYOfmyn1oUkVK7rmuiSGOoOAT50LPSOE6I1SgUgS1zIW6zz8I3dj10hpMgyvy7/XAQ78eZ0kSNNsPVIWJq6Dxf+N7sDgFdjvVuFCzOFB00zDkyvBwPvoh7c4a3dTpUDOwWgYD8029cq1n9hkGZE/xqJWgzehUH8v93rqOkfZkYJVHcCS8XbarIxqdsgnNh8qvW9k4jiKPrDv4zYvvYDCEP6iH/87utL10G5RI3TGf8WV4sF/wKIhsHnN81GFBazmUNn7ATkrNswuW+FLDQxIGA0iilmQmXwMiFg1p8blQUfIxD9tudC8tO7fQWIoHJv3nTfGSJxNoxh7Gdh7lSFiNPSX9/+VhuzNJkxSyX1cul80tpdwfWIUmHq0ZkhrUAI8h40vpazKmLprY2PYpYuSy+nROmk1Nz9aDUR1JJPMnFes5G6NAqy6PEwlQMdoBO+5sWx7cl3gVcmvuRphc8ZFPaFSWbewx11soqysGXK8C+D6PbQG2W2Fh7XS0qew7WK2bBdUNkPFEwiRnfWtA1RGjXDJWuDkiUCpy3auiSPOFPQkayqNIckiwVURaWdOkPyWpKrACRWyZj1HmxqBWkNXhWu3Bi/4wASgv8/5E541tkEC+Z005qpDly9eiUdLalwWQxvYPT4iMeNjQeq0xcFaWz8O8OFxezE="
    access_key:
      secure: "QP8EJqMHNAXT9WWv0nkFf06clsDSaudT8Oaqd0DyNCfgL8CM7t6KF5UzftMAIHJq7wFLJjydxJR/7Ndbi/SXPys6WffsUvrYesShVxb1MpzHEW9uD6XtJUk54O3olznAhiCUC2t0h44RtSuYeOsdQO2nPLaOH0uy73c1qwQLfFyoOYqCF/8MhZmMgr5SwAspMoXdmtuXifhzi6tE63Fx47Z5cVgpoZZs4P+4OV+T3g7l73u9l9wKmPwg8n8+y4+dfqkIDLruiZV8WzQ23hREFUqzMGNuxggxJ0kY0fjq6B8F49pupMwvXDehaC8uShe5f+Tz1tVTeedBsFKkxkU/niSzrdDXpjpoprCCZN5Q0nLgyd+KQpo9H7S7WodB7cOTBPGqAOzm7GFAPPUcruCLkVJU1Ugitm3UuvVA3MbRlDekXYibGbEw7pjFgp+HHJRYouiWQ6xH4cTCtnoUg9pC472qMVW6/ZLcJg9HfdC42m7Avjr3y/5FWI6JFOoPNsVw+ysVVnu7XF0vLvW6IOjPaEXzL/4X+FBdjaLR3q5PhPVMXZqQqH5BhJmFrQhn5RSl7CkqKtWIHQlpco0gMGtt1W4ctR3O5EVtONEmaVIy/SdDRWOpaF27lYT58JGrN1a3PrAsx3e7d0ixJte5Gi32hT+23yVh0ZopMzn1q4U+rYM="
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
      - graphicsmagick
      - libcairo2-dev

before_install:

  # https://github.com/npm/npm/issues/11283
  - npm set progress=false

  - npm install -g @blackbaud/skyux-cli
  - export SAVAGE_BRANCH="^savage-"
  - chmod +x ./scripts/travis-script.sh
  - chmod +x ./scripts/travis-after-failure.sh
  - chmod +x ./scripts/travis-after-script.sh
  - chmod +x ./scripts/travis-after-success.sh
  - chmod +x ./scripts/visual-baseline.sh
  - chmod +x ./scripts/visual-failures.sh

script: ./scripts/travis-script.sh
after_script: ./scripts/travis-after-script.sh
after_success:
  - ./scripts/travis-after-success.sh
  - bash <(curl -s https://blackbaud.github.io/skyux-travis/after-success.sh)

after_failure:
  - ./scripts/travis-after-failure.sh
  - ./scripts/visual-failures.sh

# When a push, only care about the master, rc-, and savage- branches.
# Otherwise anytime we commit to internal branches this would run.
branches:
  only:
    - master
    - /^rc-.*$/
    - /^savage-.*$/
    - /^[0-9]+\.[0-9]+\.[0-9]+.*/

# Cache a few things
cache:
  directories:
    - node_modules
    - $BROWSER_STACK_BINARY_BASE_PATH

notifications:
  slack:
    secure: AJd6KPL0tpgMp+tmF6ASiKtR6CW2qSXcL8H1+OVm++94n4iekdrxPX2PH97p8gmKHoyS0/qg0uBsl+Xv5HYrHe2pTFr75wj6J9KLDL5T1H9/eSowM01ugfcVZz0Lc7VqacUg3NV6NTPiLydy/XyhchT2KPIV5oQEw5FpNXj81Udo1O5fC4jhlc5SnQuHmdSRbqhXwXpOqYlyfZDW+njzJq5rIrZAKtWJOWyDR1BRtwSCuYyqMQoOS7WIzOgau5Tvx/X1YkZVohEesj1zsYd0dLkCrujkxPSHt8i5o010zlleeabz5w9lZWXreKbvA2qqHnGrIFoXftq2zPRJl4EgSBz6zDt0uTUDmOGDPHfG21pXuDTx1bwjHrV9VkjTsSp0nEmyWgJbn7EmJDo/y1cUk2+fkmuzTgn4wUqNfTMqGrQh8BKMzLG9wU3UxlHtKLgVqkeVNuEu0iZEIpcAAIbDHYbxYkUOr7pjmm/F1h/b3pojHC91UB6mdzJpSjfTCFlQsRwb2bASEvyTxuDex1bEHBnuK/kk+TeBgIplBXzBsQiEauj8mWeCmBXPaxNIagfsT4nVtBNW6ZsCoRpJC3t9CDI1DIkDtZKcxc4/KmMskunVmOliQyTY2tT86tyo1VpcZ3BI4TOd3sLwpeCX4SW25Y80N7vnXSBlaoU5JTcoUSo=
  webhooks:
    - http://sky-savage.cloudapp.net:6262/savage/travis

# Save the browserstack binary to a known location so we can cache it
env:
  global:
    - CXX=g++-4.8
    - BROWSER_STACK_BINARY_BASE_PATH=$HOME/browserstack-binary
