language: node_js
node_js:
 - "6.1"

# https://docs.travis-ci.com/user/customizing-the-build/#Git-Clone-Depth
git:
  depth: 10

# https://docs.travis-ci.com/user/languages/javascript-with-nodejs#Node.js-v4-(or-io.js-v3)-compiler-requirements
addons:
  browserstack:
    username:
      secure: "NpnkNJECej7XZT9YBuvqjryNocoVVujzt/A21roGKYa+xxWhF3d0IsLftRfOa0OM3tie8WWA+zkIcIIjavPFv2gYM52LzLQOsgxtBNHiGNNYxQyiTr+vU7bz3JVps8gXdWsDtQjIZ7pqBALsj/YLAp8ThnAcVXJa5kNv+30BHIM2odg8leqvpUrtxRLKshtdRkoK0+dw/JT4hiMWrXNvHJdh+Pn26f2ZF5nWJEURnwQTCjELQuwxTdU2cBE5OQy0SIvjZc0JM5CmXKN5purYoEUCy0/vUie3vFcjOOrEtcV6+b0AyoUgSQ1Fj7KcvFRFH1CGKdhL4R1hyfkAnPEAOVo6PCnCGj5RTd1qkYx8aHCC56xqZdDnrWnIBW8jwco9RwqPGigC2Ki6iXvS2IpyYbRC7d/7WqIRXg/67NQagkY9LjjcQvUMafGXpXYW/ua5L+/r46ag5fXCElAhsC1CPqkOfjF1ZhrDyiugdDLlXpzG6AhAb1JVX2/DXIEv+Dr1ATin8I0/m6g5C2ORNirMEtkc9rSIALrLb4QHTYyTuq1wwk/SkeSDg1X4nOu9Njyha7leMtGTAu+6mfKsPjv7FS0ZQ6ovBrFRp7eXDLsfYBNuIRPFpC7tT3tbKvoRCjdypUVn8LoeZQYEs0+VKg0nBRlKWmiHxumyrrWMcT89wB0="
    access_key:
      secure: "wSRw77uCboV1MGlzBU91FVPNIQsIqhf1LwVWv3eryl0kPbP0sn2E+N3LK7M83g4H3K198cWI4jgBko1iU1poeVmpHeGrTEMoA3HjbatHtl/lDNk6/0FCdWSwg8QI5wzXLQ5SRCiG0ZznuM5E77FAY5hz1jVMABU68BTivm1/R7fr5FgF+zOC0yNDKBtuB8ZTBtXwKZ3r0zVrYj/eNMAEkr7OdFb4JVbZPIERDRvW6JyPs4RzEjrJo9q7MLCx3m63SoKkd6PidHQGVOyHPCAJskL3W8KHFMb0rcuREKvABTv1Xkm8dMSayKxzSrkZCMNhFEPL423eAb6sRUrXEN6Fixl5O2KYmxFVBxBwYlqmf+kDfg2w1qqYLQ0js3HSMabCUidHJeKy3LS+09eNplsOyCALcMt2AERln2eX/UNimDfgKo6DOa0aBMgmfbwi2sF2z/UPrNkvsH29SwUl/IEoUiTrkVH/e5IvULQtVdj219EoygwEzfQc8x5Nf8aZLlV7WwM2gaR5EL19rsFDzUbBW8+UxZ/SZ38iER2Ul072OWKuMmXeg2LhS7wgERqT6WmdK79hck/199y5iGwJZ+RyEoLEQC47ZoWAD5hiham7QzOCu7sxFUS3dz8eSMwByTXUW+MOkMNDUCFEBcQ6VBwJ1985ib13sbho1gZaQ5JqY+s="
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
      - graphicsmagick
      - libcairo2-dev

before_install:

  # https://github.com/npm/npm/issues/11283
  - npm set progress=false

  - npm install -g @blackbaud/skyux-cli
  - export SAVAGE_BRANCH="^savage-"
  - chmod +x ./scripts/travis-script.sh
  - chmod +x ./scripts/travis-after-failure.sh
  - chmod +x ./scripts/travis-after-script.sh
  - chmod +x ./scripts/travis-after-success.sh
  - chmod +x ./scripts/visual-baseline.sh
  - chmod +x ./scripts/visual-failures.sh

script: ./scripts/travis-script.sh
after_script: ./scripts/travis-after-script.sh
after_success:
  - ./scripts/travis-after-success.sh
  - bash <(curl -s https://blackbaud.github.io/skyux-travis/after-success.sh)

after_failure:
  - ./scripts/travis-after-failure.sh
  - ./scripts/visual-failures.sh

# When a push, only care about the master, rc-, and savage- branches.
# Otherwise anytime we commit to internal branches this would run.
branches:
  only:
    - master
    - /^rc-.*$/
    - /^savage-.*$/
    - /^[0-9]+\.[0-9]+\.[0-9]+.*/

# Cache a few things
cache:
  directories:
    - node_modules
    - $BROWSER_STACK_BINARY_BASE_PATH

notifications:
  slack:
    secure: AJd6KPL0tpgMp+tmF6ASiKtR6CW2qSXcL8H1+OVm++94n4iekdrxPX2PH97p8gmKHoyS0/qg0uBsl+Xv5HYrHe2pTFr75wj6J9KLDL5T1H9/eSowM01ugfcVZz0Lc7VqacUg3NV6NTPiLydy/XyhchT2KPIV5oQEw5FpNXj81Udo1O5fC4jhlc5SnQuHmdSRbqhXwXpOqYlyfZDW+njzJq5rIrZAKtWJOWyDR1BRtwSCuYyqMQoOS7WIzOgau5Tvx/X1YkZVohEesj1zsYd0dLkCrujkxPSHt8i5o010zlleeabz5w9lZWXreKbvA2qqHnGrIFoXftq2zPRJl4EgSBz6zDt0uTUDmOGDPHfG21pXuDTx1bwjHrV9VkjTsSp0nEmyWgJbn7EmJDo/y1cUk2+fkmuzTgn4wUqNfTMqGrQh8BKMzLG9wU3UxlHtKLgVqkeVNuEu0iZEIpcAAIbDHYbxYkUOr7pjmm/F1h/b3pojHC91UB6mdzJpSjfTCFlQsRwb2bASEvyTxuDex1bEHBnuK/kk+TeBgIplBXzBsQiEauj8mWeCmBXPaxNIagfsT4nVtBNW6ZsCoRpJC3t9CDI1DIkDtZKcxc4/KmMskunVmOliQyTY2tT86tyo1VpcZ3BI4TOd3sLwpeCX4SW25Y80N7vnXSBlaoU5JTcoUSo=
  webhooks:
    - http://sky-savage.cloudapp.net:6262/savage/travis

# Save the browserstack binary to a known location so we can cache it
env:
  global:
    - CXX=g++-4.8
    - BROWSER_STACK_BINARY_BASE_PATH=$HOME/browserstack-binary
